<?php
require_once('funcoes.php');
require_once('header.php');
carrega_pagina();
    //require_once('page_home.php');
    //require_once('page_clientes.php');
require_once('footer.php');
require_once('envemail.php');
?>